"""empty message

Revision ID: 5af429264c38
Revises: 
Create Date: 2023-05-25 15:56:49.482562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5af429264c38'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expression',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('marah', sa.Integer(), nullable=True),
    sa.Column('risih', sa.Integer(), nullable=True),
    sa.Column('takut', sa.Integer(), nullable=True),
    sa.Column('senyum', sa.Integer(), nullable=True),
    sa.Column('netral', sa.Integer(), nullable=True),
    sa.Column('sedih', sa.Integer(), nullable=True),
    sa.Column('terkejut', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expression', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expression_marah'), ['marah'], unique=False)
        batch_op.create_index(batch_op.f('ix_expression_netral'), ['netral'], unique=False)
        batch_op.create_index(batch_op.f('ix_expression_risih'), ['risih'], unique=False)
        batch_op.create_index(batch_op.f('ix_expression_sedih'), ['sedih'], unique=False)
        batch_op.create_index(batch_op.f('ix_expression_senyum'), ['senyum'], unique=False)
        batch_op.create_index(batch_op.f('ix_expression_takut'), ['takut'], unique=False)
        batch_op.create_index(batch_op.f('ix_expression_terkejut'), ['terkejut'], unique=False)

    op.create_table('race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('negroid', sa.Integer(), nullable=True),
    sa.Column('east_asian', sa.Integer(), nullable=True),
    sa.Column('indian', sa.Integer(), nullable=True),
    sa.Column('latin', sa.Integer(), nullable=True),
    sa.Column('middle_eastern', sa.Integer(), nullable=True),
    sa.Column('south_east_asian', sa.Integer(), nullable=True),
    sa.Column('kaukasia', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_race_east_asian'), ['east_asian'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_indian'), ['indian'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_kaukasia'), ['kaukasia'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_latin'), ['latin'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_middle_eastern'), ['middle_eastern'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_negroid'), ['negroid'], unique=False)
        batch_op.create_index(batch_op.f('ix_race_south_east_asian'), ['south_east_asian'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_race_south_east_asian'))
        batch_op.drop_index(batch_op.f('ix_race_negroid'))
        batch_op.drop_index(batch_op.f('ix_race_middle_eastern'))
        batch_op.drop_index(batch_op.f('ix_race_latin'))
        batch_op.drop_index(batch_op.f('ix_race_kaukasia'))
        batch_op.drop_index(batch_op.f('ix_race_indian'))
        batch_op.drop_index(batch_op.f('ix_race_east_asian'))

    op.drop_table('race')
    with op.batch_alter_table('expression', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expression_terkejut'))
        batch_op.drop_index(batch_op.f('ix_expression_takut'))
        batch_op.drop_index(batch_op.f('ix_expression_senyum'))
        batch_op.drop_index(batch_op.f('ix_expression_sedih'))
        batch_op.drop_index(batch_op.f('ix_expression_risih'))
        batch_op.drop_index(batch_op.f('ix_expression_netral'))
        batch_op.drop_index(batch_op.f('ix_expression_marah'))

    op.drop_table('expression')
    # ### end Alembic commands ###
