"""empty message

Revision ID: 81d3cb19ad59
Revises: 9f384e43897d
Create Date: 2023-06-12 09:11:29.856100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81d3cb19ad59'
down_revision = '9f384e43897d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('luggage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('manusia', sa.Integer(), nullable=True),
    sa.Column('besar', sa.Integer(), nullable=True),
    sa.Column('sedang', sa.Integer(), nullable=True),
    sa.Column('kecil', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('luggage', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_luggage_besar'), ['besar'], unique=False)
        batch_op.create_index(batch_op.f('ix_luggage_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_luggage_kecil'), ['kecil'], unique=False)
        batch_op.create_index(batch_op.f('ix_luggage_manusia'), ['manusia'], unique=False)
        batch_op.create_index(batch_op.f('ix_luggage_sedang'), ['sedang'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('luggage', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_luggage_sedang'))
        batch_op.drop_index(batch_op.f('ix_luggage_manusia'))
        batch_op.drop_index(batch_op.f('ix_luggage_kecil'))
        batch_op.drop_index(batch_op.f('ix_luggage_created_at'))
        batch_op.drop_index(batch_op.f('ix_luggage_besar'))

    op.drop_table('luggage')
    # ### end Alembic commands ###
