"""empty message

Revision ID: 9f384e43897d
Revises: d688fdd864c4
Create Date: 2023-06-12 08:34:07.546760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f384e43897d'
down_revision = 'd688fdd864c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Integer(), nullable=True),
    sa.Column('pria', sa.Integer(), nullable=True),
    sa.Column('wanita', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gender', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gender_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gender_pria'), ['pria'], unique=False)
        batch_op.create_index(batch_op.f('ix_gender_wanita'), ['wanita'], unique=False)

    with op.batch_alter_table('age', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_age_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('age', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_age_created_at'))
        batch_op.alter_column('created_at',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('gender', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gender_wanita'))
        batch_op.drop_index(batch_op.f('ix_gender_pria'))
        batch_op.drop_index(batch_op.f('ix_gender_created_at'))

    op.drop_table('gender')
    # ### end Alembic commands ###
